services:
  - type: web
    name: mkportfolio
    env: php
    buildCommand: 'docker build -t symfony-app .'
    startCommand: 'docker-php-entrypoint apache2-foreground'
    envVars:
      - key: DATABASE_URL
        value: "postgresql://mkportfolio_db:CqxP3O744jSz37braib6FtnsaohOqs2C@dpg-d05a2ms9c44c739rim30-a/dbmkportfolio"

  - type: database
    name: mkportfolio_db
    engine: postgresql
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgresql://mkportfolio_db:CqxP3O744jSz37braib6FtnsaohOqs2C@dpg-d05a2ms9c44c739rim30-a/dbmkportfolio"
    database: dbmkportfolio
    user: mkportfolio_db
    password: CqxP3O744jSz37braib6FtnsaohOqs2C
